services:
  - type: web
    name: n8n-render
    env: docker
    region: frankfurt
    plan: free
    envVars:
      - key: N8N_PORT
        value: 5678
      - key: N8N_HOST
        value: 0.0.0.0
      - key: N8N_PROTOCOL
        value: http
