services:
  - type: web
    name: n8n-render
    env: node
    region: frankfurt
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: N8N_PORT
        value: 5678
      - key: N8N_PROTOCOL
        value: "http"
      - key: N8N_HOST
        value: "0.0.0.0"
