services:
  - type: web
    name: n8n
    env: docker
    plan: starter
    numInstances: 1
    healthCheckPath: /
    envVars:
      - key: DB_TYPE
        value: postgresdb
      - key: DB_POSTGRESDB_HOST
        fromDatabase:
          name: n8n-postgres
          property: host
      - key: DB_POSTGRESDB_PORT
        fromDatabase:
          name: n8n-postgres
          property: port
      - key: DB_POSTGRESDB_DATABASE
        fromDatabase:
          name: n8n-postgres
          property: database
      - key: DB_POSTGRESDB_USER
        fromDatabase:
          name: n8n-postgres
          property: user
      - key: DB_POSTGRESDB_PASSWORD
        fromDatabase:
          name: n8n-postgres
          property: password
      - key: N8N_ENCRYPTION_KEY
        generateValue: true
      - key: N8N_USER_FOLDER
        value: /data
      - key: WEBHOOK_URL
        sync: false

databases:
  - name: n8n-postgres
    plan: starter
